apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodeapp1
        image: henrikarcbox.azurecr.io/node-test-app-1:v4
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: acrpullsecret
---
apiVersion: v1
kind: Service
metadata:
  name: node-loadbalancer
spec:
  selector:
    app: nodejs
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer