apiVersion: v1
data:
  password: YWRtaW5sb2NhbA==
  username: UGFzc3dvcmQxMjMh
kind: Secret
metadata:
  name: sql1-login-secret
type: Opaque
---
apiVersion: sql.arcdata.microsoft.com/v1
kind: SqlManagedInstance
metadata:
  name: sql1
  annotations:
    exampleannotation1: exampleannotationvalue1
    exampleannotation2: exampleannotationvalue2
  labels:
    examplelabel1: examplelabelvalue1
    examplelabel2: examplelabelvalue2
spec:
  scheduling:
    default:
      resources:
        limits:
          cpu: "1"
          memory: 2Gi
        requests:
          cpu: "1"
          memory: 2Gi
  services:
    primary:
      type: LoadBalancer
  storage:
    backups:
      volumes:
      - className: local-path
        size: 5Gi
    data:
      volumes:
      - className: local-path
        size: 5Gi
    datalogs:
      volumes:
      - className: local-path
        size: 5Gi
    logs:
      volumes:
      - className: local-path
        size: 5Gi